### PR TITLE
Handle invalid initial balance

### LINKED ISSUE #116: [PE-D][Tester A] Initial balance exception
for creating account at the start , if initial balance is not a number, exception not caught

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ChenKangg/ped#6

### PR DESCRIPTION
**Pull request by ShyamKrishna33**
Display error when an invalid initial balance is entered. Fixes #116

### CODE REVIEW

File: src/main/java/budgetbuddy/storage/DataStorage.java [hunk 1]
```diff
@@ -195,10 +195,8 @@ public AccountManager loadAccounts() {
     }
 
     private AccountManager createNewAccountManager() {
-        System.out.println("Let's first create an account for you! What do you want to call it?");
```
Comment (vibes-863) [inline src/main/java/budgetbuddy/storage/DataStorage.java:198]: Good application of SLAP

**Review by vibes-863 — APPROVED** [review]
LGTM!
