### PR TITLE
Fix saveTransactions and saveAccounts method to save all objects

### LINKED ISSUE #59: Fix bug in save transaction functionality
When the user exits the program, only the latest transaction is saved. Fix the bug to properly save all the transactions.

### PR DESCRIPTION
**Pull request by ShyamKrishna33**
Fixes #59

### CODE REVIEW

File: src/main/java/budgetbuddy/storage/DataStorage.java [hunk 1]
```diff
@@ -36,7 +36,9 @@ public void saveAccounts(ArrayList<Account> accounts) {
             }
             FileWriter fw = new FileWriter(ACCOUNTS_FILE_PATH, false);
             for (Account account : accounts) {
-                fw.write(account.getAccountNumber() + " ," + account.getName() + " ," + account.getBalance() + "\n");
```
Comment (vibes-863) [inline src/main/java/budgetbuddy/storage/DataStorage.java:39]: Good job at abstracting out the code!

**Review by vibes-863 — APPROVED** [review]
LGTM
